In [46]:
import numpy as np
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

In [47]:
np.savez('array.npz',array1,array2)

In [52]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
load_array = np.load('array.npz')
array3 = np.array([[4,5,6],[1,2,3]])
np.savez('multi_array.npz',load_array['arr_0'],load_array['arr_1'],array3)


In [53]:
npzfile = np.load('multi_array.npz')
type(npzfile)


numpy.lib.npyio.NpzFile

In [54]:
npzfile.files


['arr_0', 'arr_1', 'arr_2']

In [55]:
print(npzfile['arr_0'])
print(npzfile['arr_1'])
print(npzfile['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
